version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: monitor_postgres
    environment:
      POSTGRES_DB: monitor_db
      POSTGRES_USER: monitor_user
      POSTGRES_PASSWORD: monitor_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monitor_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: monitor_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://monitor_user:monitor_password@postgres:5432/monitor_db
      FLASK_ENV: production
      FLASK_DEBUG: False
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data: